baseurl = "https://www.bloggr.net"
languageCode = "en-us"
title = "bloggR » R Programming for Data Science"
theme = "hugo-lamp-master"
googleAnalytics = "UA-145857709-1"
disqusShortname = "bloggr-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:slug/"

[params]
    description = "A blog about R programming and data science related subjects » Machine Learning | Econometrics | Bayesian Statistics. Read more!"
    logo = "/img/logo.jpg"
     github = "alexandergerber"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
  
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

[[menu.main]]
   identifier = "about"
   name = "About"
   url = "/about/"
   weight = 110

# [[menu.main]]
#    name = "Categories"
#    url = "/categories/"
#    weight = 3

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4    
    