baseurl = "/"
languageCode = "en-us"
title = "bloggR"
theme = "hugo-lamp-master"
googleAnalytics = ""
disqusShortname = "bloggr-1"
#ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    description = "A website built through Hugo and blogdown."
    logo = "/img/logo.jpg"
     github = "alexandergerber"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
  
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
   weight = -110

  [[menu.main]]
   identifier = "vitae"
    name = "Vitae"
   url = "/vitae/"
    weight = -120

