[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.56.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"



[[redirects]]
  from = "https://focused-aryabhata-2770c7.netlify.com/about/"
  to = "https://www.bloggr.net/about/"
  status = 301
  force = false
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}    
