[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.56.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://focused-aryabhata-2770c7.netlify.com/*"
  to = "https://www.bloggr.net/:splat"
  status = 301
  force = false
  query = {path = ":path"} # COMMENT: apply this rule for /old-path?path=example
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}    

[[redirects]]
  from = "https://focused-aryabhata-2770c7.netlify.com/about/"
  to = "https://www.bloggr.net/about/"
  status = 301
  force = false
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}    
